---
title: "NFI LTMP Benthic Plots"
author: "Shannon Eckhardt"
date: "2023-10-12"
output: html_document
---

# LOAD LIBRARIES & DATA
```{r}
library(tidyverse)
library(readxl)


master_data <- read_excel("/Users/Shannon/GitHub/NFI_LTMP/01_Data/Benthic_cover_March20-March23.xlsx")
# no september 2022 in this data

```

# DATA CLEANING

```{r}
# Pick out site, transect_ID and PQ
master_data <- master_data %>%
  mutate(Site = str_extract(Image_ID, "[A-Z]{2}"),
         Transect_ID = str_extract(Image_ID, "[A-Z]{2}\\d+(?=_)"),
  # extract the number before the end of string
         PQ = str_extract(Image_ID, "\\d+$")) %>% 
  dplyr::select(Image_ID, TP, Site, Transect_ID, PQ, everything()) # reorder columns
```

# CATEGORIES

Transpose data
```{r}
t.cover <- master_data %>% pivot_longer(c(ABH:`T`), names_to = "Genera", values_to = "Cover")
```
Grouping into broader categories
```{r}
benthic.cats <- t.cover %>%
  mutate(Category = 
      ifelse(Genera %in% c("ACH"),
             "Acanthastrea",
      ifelse(Genera %in% c("ABH"), 
             "Acropora_branch",
      ifelse(Genera %in% c("ANH"), 
             "Acropora_non_branch",
      ifelse(Genera %in% c("GOH"), 
             "Goniopora",
      ifelse(Genera %in% c("MEH"),
             "Montipora_encrusting",
      ifelse(Genera %in% c("MPH"),
             "Montipora_plating", 
      ifelse(Genera %in% c("OBH"),
             "Pocilloporidae", 
      ifelse(Genera %in% c("PLH"),
             "Platygyra",   
      ifelse(Genera %in% c("POH"),
             "Porites", 
      ifelse(Genera %in% c("OG"),
             "Other hard coral", 
      ifelse(Genera %in% c("S"),
             "Sand",
      ifelse(Genera %in% c("R","BARK"),
             "Rubble and Rock", 
      ifelse(Genera %in% c("Flesh", "Fol", "Dictyota", "Caulerpa", "Leath", "ACA", "CCA"),
             "Macroalgae", 
      ifelse(Genera %in% c("RT"),
             "Red Turf", 
      ifelse(Genera %in% c("T"),
             "Green Turf",
      ifelse(Genera %in% c("OtT"),
             "Other Turf",
      ifelse(Genera %in% c("BT"),
             "Black Turf",
      ifelse(Genera %in% c("ASCD", "anemo", "ESCB", "soft", "Urchin"),
             "Other benthic invertebrates",
      ifelse(Genera %in% c("NA"),
               "Other","NA"
             ))))))))))))))))))))
```
SUM counts/cover per quadrat
```{r}
groups_sum <- benthic.cats %>% 
  group_by(TP,Site,Transect_ID,PQ,Category) %>%
  summarise(Total_cover = sum(Cover))

write.csv(groups_sum, file = "/Users/Shannon/GitHub/NFI_LTMP/01_Data/Cover_per_category_per_quadrat.csv")

# search for NAs
filter(groups_sum, Category == "NA")

# no NAs because dead coral is now in the category R = Rubble
```

Specify the main groups for plotting
- Hard coral as one category and not separate genera
```{r}
cover.groups <- groups_sum  %>%
  mutate(Main_groups = 
      ifelse(Category %in% c("Acropora_branch", "Acropora_non_branch", "Acanthastrea","Goniopora","Montipora_encrusting","Montipora_plating","Pocilloporidae","Platygyra","Porites", "Other hard coral"),
             "Hard coral",
      ifelse(Category %in% c("Macroalgae"), 
             "Macroalgae",
      ifelse(Category %in% c("Other Turf"), 
             "Other Turf",
      ifelse(Category %in% c("Red Turf"), 
             "Red Turf",
      ifelse(Category %in% c("Green Turf"), 
              "Green Turf",
      ifelse(Category %in% c("Black Turf"),
               "Black Turf",
      ifelse(Category %in% c("Rubble and Rock"),
             "Rubble and Rock", 
      ifelse(Category %in% c("Sand"),
             "Sand",
      ifelse(Category %in% c("Other benthic invertebrates"),
             "Other benthic invertebrates",
      ifelse(Category %in% c("Other"),
      "Other","NA"
             )))))))))))

# SUM for main groups per quadrat
main_groups_cover_transect <- cover.groups %>% 
  group_by(TP,Site,Transect_ID, PQ, Main_groups) %>% 
  summarise(sum.PQ = sum(Total_cover))

# AVG main groups per transect
average_cover_main_groups <- main_groups_cover_transect %>% 
  group_by(TP,Site,Transect_ID,Main_groups)%>% 
  summarise(avg.cover=mean(sum.PQ))

write.csv(average_cover_main_groups, file = "/Users/Shannon/GitHub/NFI_LTMP/01_Data/NFI_transect_average_cover.csv")

# AVG cover per TP, Site (SE)
            
average_cover_all <- average_cover_main_groups %>% 
  group_by(TP,Site,Main_groups) %>% 
  summarise(avg.cover.all=mean(avg.cover),
            median_cover = median(avg.cover),
  N = n(),
  SD_cover = sd(avg.cover),
  SE_cover = sd(avg.cover/sqrt(n())))

write.csv(average_cover_all, "/Users/Shannon/GitHub/NFI_LTMP/01_DataNFI_time_site_average_cover.csv")
```


# PLOTTING

Order time points
```{r}

# Order TPs

average_cover_all$TP <- ordered(average_cover_all$TP, levels = c("March_2020","Dec_2020", "March_2021","April_2022","Dec_2022","March_2023"))

average_cover_main_groups$TP <- ordered(average_cover_main_groups$TP, levels = c("March_2020","Dec_2020","March_2021","April_2022","Dec_2022","March_2023"))

```

## EB PLOT

```{r}

# Subset EB

# Box plot 

EB_only_average_cover_all_box <- average_cover_main_groups %>% filter(Site == "EB") %>% subset(Main_groups != c("Other", "Sand")) # remove sand and other category

EB_only_average_cover_all_box$Main_groups <- ordered(EB_only_average_cover_all_box$Main_groups, levels = c("Hard coral","Macroalgae","Red Turf","Green Turf","Black Turf", "Other Turf", "Other benthic invertebrates","Rubble and Rock", "Other"))


ggplot(EB_only_average_cover_all_box, aes(x=TP, y=avg.cover)) +
  geom_boxplot() +
  theme_bw() +
  scale_y_continuous(expand = c(0, 0), limits = c(0,100)) +
  theme(axis.text.x = element_text(hjust=0.95,vjust=0.2,angle = 90)) +
    facet_grid(~Main_groups)

# # Remove March 2021 
# 
# EB_only_average_cover_all_box_minus_March_2021 <- EB_only_average_cover_all_box %>% filter(TP != "March_2021")
# 
# ggplot(EB_only_average_cover_all_box_minus_March_2021, aes(x=TP, y=avg.cover)) +
#   geom_boxplot(outlier.size = 0.1) +
#   theme_bw() +
#   scale_y_continuous(expand = c(0, 0), limits = c(0,100)) +
#   theme(axis.text.x = element_text(hjust=0.95,vjust=0.2,angle = 90)) +
#     facet_grid(~Main_groups)

# Coral groups

EB_coral <- cover.groups %>%
  filter(Main_groups == "Hard coral") %>%
  filter(Site == "EB")
  #filter(TP != "March_2021")

EB_coral_transect <- EB_coral %>% group_by(TP,Site,Transect_ID,Category) %>%
  summarise(cover = mean(Total_cover))


EB_coral_transect$Category <- ordered(EB_coral_transect$Category, levels = c("Acropora_branch","Acropora_non_branch","Montipora_encrusting","Montipora_plating","Pocilloporidae","Acanthastrea","Goniopora","Platygyra","Porites", "Other hard coral"))

EB_coral_transect$TP <- ordered(EB_coral_transect$TP, levels = c("March_2020", "Dec_2020", "March_2021", "April_2022","Dec_2022","March_2023"))

ggplot(EB_coral_transect, aes(x=TP, y=cover)) +
  geom_boxplot(outlier.size = 0.1) +
  theme_bw() +
  scale_y_continuous(expand = c(0, 0), limits = c(0,60)) +
  theme(axis.text.x = element_text(hjust=0.95,vjust=0.2,angle = 90)) +
    facet_grid(~Category)

```

